trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - ReadMe.md

name: $(Build.BuildId)

pool:
  vmImage: windows-2019

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

steps:
#- task: DotNetCoreInstaller@0
#  inputs:
#    version: '3.0.100-preview-010184'

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.9.3
  inputs:
    versionSpec: 4.9.3

- task: NuGetCommand@2
  displayName: 'NuGet restore'
#  inputs:
#    feedsToUse: config
#    nugetConfigPath: NuGet.config

- task: MSBuild@1
  displayName: Build Prism.Plugin.Popups
  inputs:
    solution: Prism.Plugin.Popups.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- powershell: ./Sign-Packages.ps1
  workingDirectory: build
  displayName: Authenticode Sign Artifacts
  env:
    SignClientUser: $(SignClientUser)
    SignClientSecret: $(SignClientSecret)
    SignClientClientId: $(SignClientClientId)
    SignClientTenantId: $(SignClientTenantId)
    SignServiceResourceId: $(SignServiceResourceId)
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: NuGet
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: |
     **\*.Tests.csproj
    arguments: -c $(BuildConfiguration) --collect:"Code Coverage" -s $(System.DefaultWorkingDirectory)/CodeCoverage.runsettings /p:DebugType=portable --no-build
  displayName: Run Tests